Bug fixes
jasp-stats/jaspCochrane pull request #3
Opened 2022-01-28 09:05 UTC by FBartos

fixes: jasp-stats/jasp-test-release#1723
fixes: jasp-stats/jasp-test-release#1709 

addresses parts of: jasp-stats/jasp-test-release#1698

2022-01-28 13:55 UTC, FBartos commented
Probably makes sense to merge to review and merge this in before: https://github.com/jasp-stats/jaspCochrane/pull/2
(I will need to update the unit tests there because some of the names and labels changed with a new scraping algorithm)

2022-01-28 14:05 UTC, Kucharssim commented
> Probably makes sense to merge to review and merge this in before: #2
(I will need to update the unit tests there because some of the names and labels changed with a new scraping algorithm)

Just to make sure that I understand correctly: You want to review this PR before https://github.com/jasp-stats/jaspCochrane/pull/2, is that right?

2022-01-28 14:08 UTC, FBartos commented
yes please

2022-01-28 14:49 UTC, Kucharssim requested changes
- [x] https://github.com/jasp-stats/jasp-test-release/issues/1723
- [x] https://github.com/jasp-stats/jasp-test-release/issues/1709
- [ ] https://github.com/jasp-stats/jasp-test-release/issues/1744

So now you display the hierarchy by unenabling the components. I still think that there could be indentation/grouping to communicate it more clearly. Something like this:

```
Distribution plot
  [ ] effect sizes
  [ ] sample sizes
  Options
    [ ] Add density
    [ ] Add rug marks
     ...
```

This is relatively minor, so I let you to decide (as it is admittedly somewhat dependent on personal preference), but I would be glad if you give it a thought.

- [ ] addresses parts of: jasp-stats/jasp-test-release#1698

In general, I like the changes you made. I have one suggestion
![Screenshot 2022-01-28 at 15 21 47](https://user-images.githubusercontent.com/7093546/151565494-94647998-edd7-4e42-83fe-3d71ed296f35.png)

It seems to me that the dropdown "Analyze as" does not really fit into that part of the form, which is focused on selecting the studies into the analysis... This option then becomes drowned in the other components and does not really logically relate to the others that surround it.

Maybe move it below the  "Selected Reviews/Meta-Analyses" list, just above the "Analyze data (individually/pooled)"?

2022-01-28 14:49 UTC, Kucharssim commented on R/cochranecommon.R
> +    if (length(selectedTitles) == 0)
Perhaps give user a feedback? Not crucial, but would be nice

2022-01-28 14:49 UTC, Kucharssim commented on inst/qml/qml_components/CochraneInput.qml
> +		title:				qsTr("Selected Reviews/Meta-Analyses")
Can you make this title and the title to `selectionType` ("Select systematic reviews based on") consistent? I assume it's either both

"Selecting systematic review/meta-analyses based on" + "Selected systematic reviews/meta-analyses"
or
"Selecting Reviews/Meta-Analyses based on" + "Selected Reviews/Meta-Analyses"

or something like that... I hope you get the gist

2022-01-28 15:18 UTC, FBartos commented
ok, I changed all parts according to the suggestions

2022-01-28 15:50 UTC, Kucharssim requested changes
Just one small thing

2022-01-28 15:50 UTC, Kucharssim commented on R/cochranecommon.R
> +        "There is no matching meta-analysis title for the specified text search", symbol = "Note: "))
```suggestion
      jaspResults[["selectedOverviewTable"]]$addFootnote(gettext(
        "There is no matching meta-analysis title for the specified text search"), symbol = "Note: ")
```

I believe this is what you wanted...

2022-01-28 21:14 UTC, FBartos commented on R/cochranecommon.R
> +        "There is no matching meta-analysis title for the specified text search", symbol = "Note: "))
oh thanks, good catch!

2022-01-31 08:39 UTC, Kucharssim approved these changes

2022-01-31 08:40 UTC, merged